# Generated by Django 5.1.5 on 2025-01-31 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_css', models.TextField(verbose_name='프레임 css')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=150, verbose_name='댓글 본문')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='제목')),
                ('date', models.DateField(verbose_name='날짜')),
                ('place', models.CharField(max_length=40, verbose_name='장소')),
                ('emotion', models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점'), (6, '6점'), (7, '7점')], verbose_name='감정지수')),
                ('content', models.TextField(verbose_name='일기 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('comments', models.ManyToManyField(related_name='commented_diaries', through='diaries.Comment', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wirte_diaries', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('four_cut_photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diaries.frame')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.diary'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.diary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'diary')},
            },
        ),
        migrations.AddField(
            model_name='diary',
            name='likers',
            field=models.ManyToManyField(related_name='liked_diaries', through='diaries.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/user_photos/%Y/%m/%d', verbose_name='사진')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='diaries.frame')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_image', models.FilePathField(verbose_name='스티커 이미지')),
                ('coor_x', models.FloatField(verbose_name='x좌표')),
                ('coor_y', models.FloatField(verbose_name='y좌표')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='diaries.frame')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='태그명')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='diaries.diary', verbose_name='일기')),
            ],
        ),
        migrations.CreateModel(
            name='User_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='태그 시간')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_diaries', to='diaries.diary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('diary', 'user')},
            },
        ),
        migrations.AddField(
            model_name='diary',
            name='user_tags',
            field=models.ManyToManyField(related_name='tagged_diaries', through='diaries.User_Tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
