# Generated by Django 5.1.5 on 2025-02-01 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_rename_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='weather',
            field=models.CharField(choices=[('sunny', '맑음'), ('partly_cloudy', '구름많음'), ('cloudy', '흐림'), ('rainy', '비'), ('snowy', '눈'), ('windy', '바람')], default='sunny', max_length=20, verbose_name='날씨'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='날짜'),
        ),
    ]
