# Generated by Django 5.1.5 on 2025-02-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_diary_weather_alter_diary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='logo_text',
            field=models.CharField(default='pictory', max_length=20, verbose_name='로고 text'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='sticker_image',
            field=models.FilePathField(match='.*\\.(png|jpg|jpeg|gif|webp|bmp|tiff)$', path='static/images/stickers', recursive=True, verbose_name='스티커 이미지'),
        ),
    ]
