# Generated by Django 5.1.5 on 2025-02-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_frame_logo_text_alter_sticker_sticker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='image_file',
            field=models.ImageField(default='None', upload_to='images/frames/%Y/%m/%d', verbose_name='최종 이미지 파일'),
            preserve_default=False,
        ),
    ]
