# Generated by Django 5.1.5 on 2025-02-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0006_diary_address'),
        ('diaries', '0006_diary_place_address'),
    ]

    operations = [
    ]
