# Generated by Django 5.1.5 on 2025-02-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_merge_0006_diary_address_0006_diary_place_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='address',
        ),
    ]
