# Generated by Django 5.1.5 on 2025-02-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0008_remove_diary_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='태그명'),
        ),
    ]
