# Generated by Django 5.1.5 on 2025-02-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0009_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='frame_css',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='logo_text',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Sticker',
        ),
    ]
