# Generated by Django 5.1.5 on 2025-02-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0010_remove_sticker_frame_remove_frame_frame_css_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='four_cut_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='diaries.frame', verbose_name='프레임'),
        ),
    ]
