# Generated by Django 5.1.5 on 2025-01-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='images/default_images/default_profile_photo.png', upload_to='images/users/profile_photo/%Y/%m/%d', verbose_name='프로필 사진'),
        ),
    ]
