# Generated by Django 5.1.5 on 2025-01-31 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField(match='.*\\.(png|jpg|jpeg|gif|webp|bmp|tiff)$', path='static/images/badges', recursive=True, verbose_name='배지 이미지')),
                ('description', models.CharField(max_length=30, verbose_name='배지 설명')),
            ],
        ),
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors1', to=settings.AUTH_USER_MODEL, verbose_name='이웃 A')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors2', to=settings.AUTH_USER_MODEL, verbose_name='이웃 B')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user1', 'user2'), name='unique_neighbor')],
            },
        ),
        migrations.CreateModel(
            name='NeighborRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', '대기 중'), ('accepted', '수락됨')], default='waiting', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_neighbor_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청 받은 유저')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_neighbor_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청 보낸 유저')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
