# Generated by Django 5.1.5 on 2025-02-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_badge_neighbor_neighborrequest_userbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborrequest',
            name='status',
        ),
    ]
