# Generated by Django 5.1.5 on 2025-02-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0008_remove_diary_address'),
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_TAG',
            fields=[
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tag_notification', serialize=False, to='users.notification')),
                ('tagged_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to='diaries.diary')),
            ],
        ),
    ]
