# Generated by Django 5.1.5 on 2025-02-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_introduce_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='소개'),
        ),
    ]
