# Generated by Django 5.1.5 on 2025-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(max_length=50, verbose_name='배지 설명'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='식별자'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYS', 'system'), ('NFR', 'new friend request'), ('FRA', 'friend request accepted'), ('TAG', 'tagged'), ('NBA', 'new badge acquire')], default='SYS', max_length=10, verbose_name='알림 타입'),
        ),
    ]
