# Generated by Django 5.1.5 on 2025-02-11 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_badge_description_alter_badge_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_NBA',
            fields=[
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nba_notification', serialize=False, to='users.notification')),
                ('acquired_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to='users.badge')),
            ],
        ),
    ]
